import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import os from "node:os";
import { DEFAULT_SETTINGS } from "./defaults";
import { SETTINGS_METADATA } from "./metadata";
import { SettingsService, SettingsModuleName, SETTINGS_MODULES, isSettingsModuleName, redactSensitiveSettings } from "./service";
import { BrMediaSettings } from "./types";
import { validateSettings } from "./validation";

export const SETTINGS_EXPORT_FORMAT = "brmedia-settings-export";
export const SETTINGS_EXPORT_FORMAT_VERSION = 1;
export const SETTINGS_IMPORT_MAX_BYTES = 1024 * 1024;
export const SETTINGS_IMPORT_MAX_DEPTH = 32;
export const SETTINGS_IMPORT_MAX_NODES = 10000;
const BACKUP_RE=/^settings-(\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2})-([a-f0-9]{8})\.json$/;
const BAD_KEYS=new Set(["__proto__","constructor","prototype"]);
type Obj=Record<string,unknown>;
function rec(v:unknown):v is Obj{return typeof v==="object"&&v!==null&&!Array.isArray(v)}
function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v)) as T}
function merge(a:unknown,b:unknown):unknown{if(!rec(a)||!rec(b))return clone(b);const o:Obj=clone(a);for(const[k,v]of Object.entries(b))o[k]=rec(v)&&rec(o[k])?merge(o[k],v):clone(v);return o}
function inspect(v:unknown,d=0,c={n:0}):void{if(d>SETTINGS_IMPORT_MAX_DEPTH)throw new Error("IMPORT_TOO_DEEP");if(++c.n>SETTINGS_IMPORT_MAX_NODES)throw new Error("IMPORT_TOO_COMPLEX");if(rec(v)){for(const[k,x]of Object.entries(v)){if(BAD_KEYS.has(k))throw new Error("UNSAFE_OBJECT_KEY");inspect(x,d+1,c)}}else if(Array.isArray(v))for(const x of v)inspect(x,d+1,c)}
function flatten(v:unknown,p="",out=new Map<string,unknown>()):Map<string,unknown>{if(rec(v)){for(const[k,x]of Object.entries(v))flatten(x,p?`${p}.${k}`:k,out)}else out.set(p,v);return out}
function changed(before:unknown,after:unknown){const a=flatten(before),b=flatten(after);const added:string[]=[],changed:string[]=[],unchanged:string[]=[];for(const[k,v]of b){if(!a.has(k))added.push(k);else if(JSON.stringify(a.get(k))===JSON.stringify(v))unchanged.push(k);else changed.push(k)}return{added,changed,unchanged}}
function stable(v:unknown):unknown{if(Array.isArray(v))return v.map(stable);if(rec(v))return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v}
function sensitive(pathName:string){return SETTINGS_METADATA[pathName]?.sensitive===true}
function preserveRedacted(current:unknown,incoming:unknown,p=""):unknown{if(sensitive(p)&&incoming==="[REDACTED]")return clone(current);if(rec(current)&&rec(incoming)){const o:Obj={};for(const[k,v]of Object.entries(incoming))o[k]=preserveRedacted(current[k],v,p?`${p}.${k}`:k);return o}return clone(incoming)}
export interface ExportEnvelope{format:string;exportFormatVersion:number;settingsSchemaVersion:number;brmediaVersion:string;exportedAt:string;includedModules:string[];redacted:boolean;sourcePlatform:string;settings:Obj}
export interface ImportPreview{valid:boolean;errors:string[];warnings:string[];formatVersion:number|null;sourceSchemaVersion:number|null;targetSchemaVersion:number;includedModules:string[];added:string[];changed:string[];unchanged:string[];unknown:string[];invalid:unknown[];redacted:string[];restartRequired:string[];pageReloadRequired:string[];candidate?:BrMediaSettings}
export class SettingsManagementService{
 constructor(private readonly service=new SettingsService()){}
 private store(){return this.service.getStore()}
 private audit(settings:BrMediaSettings,operation:string,module:string|null,backupId?:string){const file=path.join(path.dirname(this.store().settingsPath),"settings-audit.jsonl");fs.mkdirSync(path.dirname(file),{recursive:true});let rows:string[]=[];if(fs.existsSync(file))rows=fs.readFileSync(file,"utf8").split(/\r?\n/).filter(Boolean);rows.push(JSON.stringify({timestamp:new Date().toISOString(),operation,module,validation:"valid",backupId:backupId??null,success:true}));rows=rows.slice(-settings.backup.auditHistoryLimit);fs.writeFileSync(file,rows.join("\n")+"\n","utf8")}
 private backupDir(settings:BrMediaSettings){return settings.backup.backupLocation?path.resolve(settings.backup.backupLocation):path.join(path.dirname(this.store().settingsPath),"backups")}
 export(module?:SettingsModuleName,administrative=false):ExportEnvelope{const snap=this.service.readAll(!administrative);const settings=module?{schemaVersion:snap.data.schemaVersion,[module]:snap.data[module]} as Obj:snap.data as unknown as Obj;return{format:SETTINGS_EXPORT_FORMAT,exportFormatVersion:1,settingsSchemaVersion:snap.data.schemaVersion,brmediaVersion:"0.0.1",exportedAt:new Date().toISOString(),includedModules:module?[module]:[...SETTINGS_MODULES],redacted:!administrative,sourcePlatform:os.platform(),settings}}
 serializeExport(module?:SettingsModuleName){return JSON.stringify(stable(this.export(module,false)),null,2)+"\n"}
 preview(input:unknown,selected?:string[]):ImportPreview{const errors:string[]=[],warnings:string[]=[];let parsed:unknown=input;try{if(typeof input==="string"){if(Buffer.byteLength(input)>SETTINGS_IMPORT_MAX_BYTES)throw new Error("IMPORT_TOO_LARGE");parsed=JSON.parse(input)}inspect(parsed)}catch(e){return{valid:false,errors:[e instanceof Error?e.message:String(e)],warnings,formatVersion:null,sourceSchemaVersion:null,targetSchemaVersion:DEFAULT_SETTINGS.schemaVersion,includedModules:[],added:[],changed:[],unchanged:[],unknown:[],invalid:[],redacted:[],restartRequired:[],pageReloadRequired:[]}}
  if(!rec(parsed)||parsed.format!==SETTINGS_EXPORT_FORMAT||parsed.exportFormatVersion!==1||!rec(parsed.settings))errors.push("UNSUPPORTED_EXPORT_FORMAT");const source=rec(parsed)&&typeof parsed.settingsSchemaVersion==="number"?parsed.settingsSchemaVersion:null;if(source===null)errors.push("MISSING_SCHEMA_VERSION");else if(source>DEFAULT_SETTINGS.schemaVersion)errors.push("NEWER_SCHEMA_UNSUPPORTED");else if(source<DEFAULT_SETTINGS.schemaVersion)warnings.push("OLDER_SCHEMA_REQUIRES_EXPLICIT_COMPATIBILITY");const current=this.service.readAll(false).data;let candidate=clone(current);const incoming=rec(parsed)&&rec(parsed.settings)?parsed.settings:{};const mods=(selected??(rec(parsed)&&Array.isArray(parsed.includedModules)?parsed.includedModules:SETTINGS_MODULES)).filter((x):x is SettingsModuleName=>typeof x==="string"&&isSettingsModuleName(x));for(const m of mods)if(m in incoming)candidate[m]=preserveRedacted(current[m],incoming[m],m) as never;const validation=validateSettings(candidate);const moduleErrors=mods.flatMap(m=>m in incoming&&JSON.stringify(current[m])!==JSON.stringify(candidate[m])?this.service.validateModuleUpdate(m,incoming[m]).errors:[]);const diff=changed(current,candidate);const redacted=[...flatten(incoming)].filter(([p,v])=>v==="[REDACTED]"||sensitive(p)).map(([p])=>p);const restart=diff.changed.filter(p=>SETTINGS_METADATA[p]?.restartRequired==="server-restart");const reload=diff.changed.filter(p=>SETTINGS_METADATA[p]?.pageReloadRequired||SETTINGS_METADATA[p]?.restartRequired==="page-reload");return{valid:errors.length===0&&validation.valid&&moduleErrors.length===0,errors,warnings,formatVersion:rec(parsed)&&typeof parsed.exportFormatVersion==="number"?parsed.exportFormatVersion:null,sourceSchemaVersion:source,targetSchemaVersion:DEFAULT_SETTINGS.schemaVersion,includedModules:mods,added:diff.added,changed:diff.changed,unchanged:diff.unchanged,unknown:validation.unknownSettings.map(x=>x.path),invalid:[...validation.errors,...moduleErrors],redacted,restartRequired:restart,pageReloadRequired:reload,candidate:validation.valid?candidate:undefined}}
 private createBackup(settings:BrMediaSettings,operation:string){const dir=this.backupDir(settings);fs.mkdirSync(dir,{recursive:true});const id=`settings-${new Date().toISOString().slice(0,19).replace(/:/g,"-")}-${crypto.randomBytes(4).toString("hex")}.json`;const file=path.join(dir,id);fs.writeFileSync(file,JSON.stringify({id,createdAt:new Date().toISOString(),operation,schemaVersion:settings.schemaVersion,settings},null,2)+"\n",{encoding:"utf8",flag:"wx"});this.prune(dir,settings.backup.retentionCount);return id}
 private prune(dir:string,keep:number){const files=fs.readdirSync(dir).filter(x=>BACKUP_RE.test(x)).sort().reverse();for(const x of files.slice(Math.max(1,keep)))fs.unlinkSync(path.join(dir,x))}
 async apply(input:unknown,selected?:string[]){const p=this.preview(input,selected);if(!p.valid||!p.candidate)return{ok:false,preview:p};let backupId:string|undefined;const snap=await this.store().update(current=>{if(current.backup.automaticBackupEnabled&&current.backup.automaticBackupBeforeImport)backupId=this.createBackup(current,"import");return p.candidate!});this.audit(snap.settings,"import",selected?.join(",")??"all",backupId);return{ok:true,backupId,settings:redactSensitiveSettings(snap.settings),restartRequired:p.restartRequired,pageReloadRequired:p.pageReloadRequired}}
 listBackups(){const s=this.service.readAll(false).data,dir=this.backupDir(s);if(!fs.existsSync(dir))return[];return fs.readdirSync(dir).filter(x=>BACKUP_RE.test(x)).sort().reverse().slice(0,s.backup.retentionCount).map(id=>{try{const st=fs.statSync(path.join(dir,id));const o=JSON.parse(fs.readFileSync(path.join(dir,id),"utf8"));return{id,createdAt:o.createdAt??st.mtime.toISOString(),schemaVersion:o.schemaVersion??null,size:st.size,healthy:rec(o)&&rec(o.settings)}}catch{return{id,createdAt:null,schemaVersion:null,size:0,healthy:false}}})}
 private readBackup(id:string){if(!BACKUP_RE.test(id))throw new Error("INVALID_BACKUP_ID");const s=this.service.readAll(false).data;const file=path.join(this.backupDir(s),id);const parsed=JSON.parse(fs.readFileSync(file,"utf8"));if(!rec(parsed)||!rec(parsed.settings))throw new Error("CORRUPT_BACKUP");return parsed.settings}
 previewBackup(id:string){const settings=this.readBackup(id);return this.preview({format:SETTINGS_EXPORT_FORMAT,exportFormatVersion:1,settingsSchemaVersion:(settings as Obj).schemaVersion,includedModules:[...SETTINGS_MODULES],settings})}
 async restore(id:string){const p=this.previewBackup(id);if(!p.valid||!p.candidate)return{ok:false,preview:p};let backupId:string|undefined;const snap=await this.store().update(current=>{if(current.backup.automaticBackupBeforeRestore)backupId=this.createBackup(current,"pre-restore");return p.candidate!});this.audit(snap.settings,"restore",id,backupId);return{ok:true,backupId,settings:redactSensitiveSettings(snap.settings),preview:p}}
 resetPreview(target:string){const current=this.service.readAll(false).data;const parts=target.split(".");let def:unknown=DEFAULT_SETTINGS,old:unknown=current;for(const x of parts){if(!rec(def)||!rec(old)||!(x in def))throw new Error("UNKNOWN_RESET_TARGET");def=def[x];old=old[x]}return{target,old:sensitive(target)?"[REDACTED]":old,value:sensitive(target)?"[REDACTED]":def,...changed(old,def)}}
 async reset(target:string,preserveUnknown=true){const preview=this.resetPreview(target);let backupId:string|undefined;const snap=await this.store().update(current=>{if(current.backup.automaticBackupBeforeReset)backupId=this.createBackup(current,"reset");const next=clone(current);const parts=target.split(".");let n:Obj=next as unknown as Obj,d:unknown=DEFAULT_SETTINGS;for(let i=0;i<parts.length-1;i++){n=n[parts[i]] as Obj;d=(d as Obj)[parts[i]]}const key=parts[parts.length-1];const dv=(d as Obj)[key];n[key]=preserveUnknown&&rec(n[key])&&rec(dv)?merge(n[key],dv):clone(dv);return next});this.audit(snap.settings,"reset",target,backupId);return{ok:true,backupId,preview,settings:redactSensitiveSettings(snap.settings)}}
 async resetAll(preserveUnknown=true){let backupId:string|undefined;const snap=await this.store().update(current=>{if(current.backup.automaticBackupBeforeReset)backupId=this.createBackup(current,"reset-all");return preserveUnknown?merge(current,DEFAULT_SETTINGS) as unknown as BrMediaSettings:clone(DEFAULT_SETTINGS)});return{ok:true,backupId,settings:redactSensitiveSettings(snap.settings)}}
 async recover(source:"last-known-good"|"defaults"|"historical",id?:string){let candidate:BrMediaSettings;if(source==="defaults")candidate=clone(DEFAULT_SETTINGS);else if(source==="historical"&&id)candidate=this.readBackup(id) as unknown as BrMediaSettings;else if(source==="last-known-good"){candidate=JSON.parse(fs.readFileSync(this.store().backupPath,"utf8")) as BrMediaSettings}else throw new Error("INVALID_RECOVERY_SOURCE");const validation=validateSettings(candidate);if(!validation.valid)throw new Error("INVALID_RECOVERY_SOURCE");const snap=await this.store().recover(candidate);this.audit(snap.settings,"recovery",source);return{ok:true,settings:redactSensitiveSettings(snap.settings),health:snap.health}}
 recoveryStatus(){const h=this.service.health();return{health:h,sources:{lastKnownGood:h.backupExists,historical:this.listBackups().length,defaults:true},actionRequired:h.state==="invalid"||h.state==="recovered-from-backup"}}
}