import assert from "node:assert/strict";import test from "node:test";import { createDjAnalysisCompatibilityMetadata, inspectDjAnalysisCompatibility } from "./djAnalysisCompatibility";import { DJ_BPM_ANALYSIS_FORMAT_VERSION } from "./djBpmAnalysis";import { DJ_DOWNBEAT_ANALYSIS_FORMAT_VERSION } from "./djDownbeatAnalysis";import { DJ_DYNAMIC_ANALYSIS_FORMAT_VERSION } from "./djDynamicAnalysis";import { DJ_BEAT_DETECTION_FORMAT_VERSION } from "./djBeatDetection";import { DJ_GRID_VALIDATION_FORMAT_VERSION } from "./djGridValidation";import { DJ_FINAL_GRID_DECISION_FORMAT_VERSION } from "./djFinalGridDecision";
import { createDjImplementationFingerprint, DJ_IMPLEMENTATION_VERSIONS } from "./djPreparedAssets";
function current(){return {formatVersion:"prepared-analysis-v1",confidence:{windows:[1],coverage:1,energy:1,transients:1,overall:1},bpmAnalysis:{formatVersion:DJ_BPM_ANALYSIS_FORMAT_VERSION,confidence:.8},beatDetection:{formatVersion:DJ_BEAT_DETECTION_FORMAT_VERSION,coverage:.8,stability:.8},downbeatAnalysis:{formatVersion:DJ_DOWNBEAT_ANALYSIS_FORMAT_VERSION,downbeatConfidence:.8,phraseAgreement:.8},dynamicAnalysis:{formatVersion:DJ_DYNAMIC_ANALYSIS_FORMAT_VERSION,constantBpmConfidence:.8,dynamicConfidence:.2},gridValidation:{formatVersion:DJ_GRID_VALIDATION_FORMAT_VERSION,confidenceAfter:.8},finalGridDecision:{formatVersion:DJ_FINAL_GRID_DECISION_FORMAT_VERSION,finalConfidence:.8},compatibility:createDjAnalysisCompatibilityMetadata()};}
test("B11 legacy analysis loads with notice",()=>{const i=current();delete (i as any).compatibility;const r=inspectDjAnalysisCompatibility(i);assert.equal(r.status,"legacy-compatible");assert.equal(r.loadable,true);});
test("B11 current analysis loads normally",()=>{const r=inspectDjAnalysisCompatibility(current());assert.equal(r.status,"current");assert.equal(r.action,"use");});
test("B11 future schema is rejected gracefully",()=>{const i=current();(i.compatibility as any).schemaVersion=2;const r=inspectDjAnalysisCompatibility(i);assert.equal(r.status,"unsupported-future");assert.equal(r.loadable,false);});
test("B11 damaged metadata never crashes",()=>{const r=inspectDjAnalysisCompatibility("broken");assert.equal(r.status,"damaged");assert.equal(r.action,"reject");});
test("B11 missing metadata is structured",()=>{const r=inspectDjAnalysisCompatibility(null);assert.equal(r.status,"missing");assert.equal(r.reanalysis.recommended,true);});
test("B11 invalid confidence rejects only its nested stage",()=>{const i=current();i.bpmAnalysis.confidence=4;const r=inspectDjAnalysisCompatibility(i);assert.equal(r.loadable,true);assert.ok(r.rejectedFields.includes("bpmAnalysis"));assert.equal(r.sanitisedAnalysis?.bpmAnalysis,undefined);});
test("B11 invalid canonical confidence rejects the record",()=>{const i=current();i.confidence.overall=NaN;assert.equal(inspectDjAnalysisCompatibility(i).loadable,false);});
test("B11 migration defaults are preview-only",()=>{const i=current();delete (i as any).compatibility;const r=inspectDjAnalysisCompatibility(i);assert.equal(r.migration.available,true);assert.equal(r.migration.performed,false);assert.equal(r.migration.mayWrite,false);assert.equal(r.migration.preservesWaveform,true);});
test("B11 missing strengthened stages recommend reanalysis without starting",()=>{const i=current();delete (i as any).gridValidation;delete (i as any).finalGridDecision;const r=inspectDjAnalysisCompatibility(i);assert.equal(r.reanalysis.recommended,true);assert.equal(r.reanalysis.mayAutoStart,false);});
test("B11 manual grid remains authoritative",()=>{const r=inspectDjAnalysisCompatibility(current(),{manual:true});assert.equal(r.protection.decision,"manual-grid-authoritative");assert.equal(r.migration.mayWrite,false);});
test("B11 locked grid remains authoritative",()=>{const i=current();delete (i as any).gridValidation;const r=inspectDjAnalysisCompatibility(i,{locked:true});assert.equal(r.reanalysis.policy,"review-only");assert.equal(r.protection.decision,"locked-grid-authoritative");});
test("B11 unknown nested version is omitted safely",()=>{const i=current();i.gridValidation.formatVersion="future" as any;const r=inspectDjAnalysisCompatibility(i);assert.equal(r.loadable,true);assert.equal(r.sanitisedAnalysis?.gridValidation,undefined);assert.ok(r.diagnostics.unsupportedVersions.includes("future"));});
test("B11 compatibility decisions are deterministic and pure",()=>{const i=current(),before=JSON.stringify(i),a=inspectDjAnalysisCompatibility(i),b=inspectDjAnalysisCompatibility(i);assert.deepEqual(a,b);assert.equal(JSON.stringify(i),before);});

test("B11 policy version does not invalidate existing prepared assets",()=>{const changed={...DJ_IMPLEMENTATION_VERSIONS,analysisCompatibility:"strengthened-analysis-future"};for(const type of ["prepared-waveform","waveform-detail","prepared-analysis","bpm-analysis","beat-detection","downbeat-analysis","dynamic-analysis","grid-validation","final-grid-decision","beat-grid"] as const)assert.equal(createDjImplementationFingerprint(type).value,createDjImplementationFingerprint(type,changed).value);});
