import { combineDjConfidence, normaliseDjConfidence } from "./djAnalysisConfidence";
import { DjBpmAnalysisResult, DjCanonicalBpmInput, DjOnsetCandidate, selectDjOnsetCandidates } from "./djBpmAnalysis";

export const DJ_BEAT_DETECTION_FORMAT_VERSION = "beat-refinement-v1";
export const DJ_BEAT_DETECTION_MAX_CANDIDATES = 8192;

export type DjBeatCharacter = "kick-like" | "snare-like" | "percussive" | "bass-attack" | "melodic-attack" | "uncertain";
export type DjBeatCandidate = DjOnsetCandidate & { validationConfidence: number; spacingConfidence: number; contextConfidence: number; character: DjBeatCharacter; reasonCodes: string[] };
export type DjBeatDetectionResult = { formatVersion: typeof DJ_BEAT_DETECTION_FORMAT_VERSION; candidates: DjBeatCandidate[]; candidateCount: number; rejectedCount: number; duplicateCount: number; coverage: number; stability: number; digitalStability: number; liveTolerance: number; reasonCodes: string[]; analysedAt: string };
export type DjBeatDetectionInput = DjCanonicalBpmInput & { bpmAnalysis: DjBpmAnalysisResult; lowBand?: readonly number[]; midBand?: readonly number[]; highBand?: readonly number[] };

function resample(values: readonly number[] | undefined, count: number): number[] { if (!values?.length) return new Array(count).fill(0); return Array.from({length:count},(_,i)=>{const p=i/Math.max(1,count-1)*(values.length-1),l=Math.floor(p),r=Math.min(values.length-1,l+1),f=p-l;return normaliseDjConfidence((Number(values[l])||0)*(1-f)+(Number(values[r])||0)*f);}); }
function median(values: readonly number[]): number { const a=values.filter(Number.isFinite).slice().sort((x,y)=>x-y); if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2; }
function character(low:number,mid:number,high:number,energyRise:number):DjBeatCharacter { const total=low+mid+high+.000001;if(low/total>=.52)return energyRise>.12?"kick-like":"bass-attack";if((mid+high)/total>=.72&&high>.12)return "snare-like";if(high/total>=.42)return "percussive";if(energyRise>.16)return "melodic-attack";return "uncertain"; }

export function refineDjBeatCandidates(input:DjBeatDetectionInput):DjBeatDetectionResult {
 const analysedAt=input.analysedAt||input.bpmAnalysis.analysedAt||new Date().toISOString(),duration=Math.max(0,Number(input.duration)||0),count=Math.min(131072,Math.max(input.transients.length,input.energyWindows.length,input.normalizedAmplitude.length));
 const empty:DjBeatDetectionResult={formatVersion:DJ_BEAT_DETECTION_FORMAT_VERSION,candidates:[],candidateCount:0,rejectedCount:0,duplicateCount:0,coverage:0,stability:0,digitalStability:0,liveTolerance:0,reasonCodes:["insufficient-prepared-detail"],analysedAt};if(!duration||count<32||!input.bpmAnalysis.bpm)return empty;
 const raw=selectDjOnsetCandidates(input),energy=resample(input.energyWindows,count),amplitude=resample(input.normalizedAmplitude,count),low=resample(input.lowBand,count),mid=resample(input.midBand,count),high=resample(input.highBand,count),fps=count/duration,period=60/Number(input.bpmAnalysis.bpm),spacingSamples=period*fps,minSpacing=Math.max(1,Math.floor(spacingSamples*.28));
 const provisional:DjBeatCandidate[]=[];let rejected=0,duplicates=0;
 for(let position=0;position<raw.length;position++){const onset=raw[position],i=onset.index,radius=Math.max(2,Math.floor(fps*.08)),before=energy.slice(Math.max(0,i-radius),i),after=energy.slice(i+1,Math.min(count,i+radius+1)),surrounding=median([...before,...after]),energyRise=Math.max(0,energy[i]-median(before)),isolated=Math.max(0,onset.strength-surrounding),clipped=amplitude[i]>.985&&median([...before,...after].map((_,offset)=>amplitude[Math.max(0,i-radius+offset)]))>.94;let spacing=0;for(const neighbour of [raw[position-2],raw[position-1],raw[position+1],raw[position+2]]){if(!neighbour)continue;const beats=Math.max(1,Math.round(Math.abs(neighbour.time-onset.time)/period)),error=Math.abs(Math.abs(neighbour.time-onset.time)-beats*period)/period;spacing=Math.max(spacing,normaliseDjConfidence(1-error/0.24));}
 const context=normaliseDjConfidence(Math.max(energy[i],surrounding)*.58+energyRise*.42);const spikePenalty=isolated>.72&&context<.28?.38:1,clipPenalty=clipped?.48:1;const validation=combineDjConfidence([{id:"transient-quality",value:onset.confidence,weight:1.4},{id:"musical-context",value:context,weight:1.2},{id:"beat-spacing",value:spacing,weight:1.5,repetitions:spacing>.6?3:1},{id:"isolated-spike",value:1-spikePenalty,weight:.8,polarity:"conflict"},{id:"clipping",value:1-clipPenalty,weight:.7,polarity:"conflict"}]);if(validation<.34||(spacing<.22&&context<.3)){rejected++;continue;}const candidate:DjBeatCandidate={...onset,validationConfidence:validation,spacingConfidence:spacing,contextConfidence:context,character:character(low[i],mid[i],high[i],energyRise),reasonCodes:[...(clipped?["clipping-suppressed"]:[]),...(spacing<.45?["weak-spacing-support"]:[]),...(context<.38?["quiet-section"]:[])]};const previous=provisional[provisional.length-1];if(previous&&candidate.index-previous.index<minSpacing){duplicates++;if(candidate.validationConfidence*candidate.strength>previous.validationConfidence*previous.strength)provisional[provisional.length-1]=candidate;continue;}provisional.push(candidate);if(provisional.length>=DJ_BEAT_DETECTION_MAX_CANDIDATES)break;}
 const intervals=provisional.slice(1).map((item,index)=>{const beats=Math.max(1,Math.round((item.time-provisional[index].time)/period));return Math.abs((item.time-provisional[index].time)-beats*period)/period;}),stability=normaliseDjConfidence(1-median(intervals)/.2),coverage=normaliseDjConfidence(provisional.length/Math.max(1,duration/period)*1.4),digitalStability=normaliseDjConfidence(stability*.62+Number(input.bpmAnalysis.exactDigitalConfidence||0)*.38),liveTolerance=normaliseDjConfidence(stability*.45+coverage*.35+Number(input.bpmAnalysis.sectionAgreement||0)*.2);const reasons:string[]=[];if(coverage<.35)reasons.push("sparse-rhythmic-coverage");if(stability<.5)reasons.push("variable-or-noisy-spacing");if(digitalStability>.82)reasons.push("digitally-stable-sequence");return {formatVersion:DJ_BEAT_DETECTION_FORMAT_VERSION,candidates:provisional,candidateCount:provisional.length,rejectedCount:rejected,duplicateCount:duplicates,coverage,stability,digitalStability,liveTolerance,reasonCodes:reasons,analysedAt};
}
