import assert from "node:assert/strict";import test from "node:test";import { refineDjBeatCandidates } from "./djBeatDetection";
import { createDjImplementationFingerprint, DJ_IMPLEMENTATION_VERSIONS } from "./djPreparedAssets";
function fixture(options:{bpm?:number;quietIntro?:boolean;duplicates?:boolean;clipped?:boolean;jitter?:number}={}){const bpm=options.bpm||170,duration=90,fps=100,count=duration*fps,transients=new Array(count).fill(0),energyWindows=new Array(count).fill(.03),normalizedAmplitude=new Array(count).fill(.04),windowConfidence=new Array(count).fill(1),lowBand=new Array(count).fill(.04),midBand=new Array(count).fill(.02),highBand=new Array(count).fill(.01);let beat=0;for(let t=.4;t<duration;t+=60/bpm){const jitter=(options.jitter||0)*(beat%2?1:-1),i=Math.round((t+jitter)*fps);if(options.quietIntro&&t<12){beat++;continue;}transients[i]=1;energyWindows[i]=.78;normalizedAmplitude[i]=options.clipped?.995:.82;lowBand[i]=.9;if(options.duplicates&&i+3<count){transients[i+3]=.82;energyWindows[i+3]=.5;}beat++;}return {duration,transients,energyWindows,normalizedAmplitude,windowConfidence,lowBand,midBand,highBand,analysedAt:"2026-07-27T00:00:00.000Z",bpmAnalysis:{bpm,analysedAt:"2026-07-27T00:00:00.000Z",exactDigitalConfidence:options.jitter?0:.9,sectionAgreement:1} as any};}
test("B8 stable digital beats produce deterministic candidates",()=>{const input=fixture(),a=refineDjBeatCandidates(input),b=refineDjBeatCandidates(input);assert.deepEqual(a,b);assert.ok(a.candidateCount>100);assert.ok(a.digitalStability>.8);});
test("B8 duplicate detections collapse to one rhythmic event",()=>{const base=refineDjBeatCandidates(fixture()),dup=refineDjBeatCandidates(fixture({duplicates:true}));assert.ok(dup.candidateCount<=base.candidateCount+1);});
test("B8 isolated click noise is rejected",()=>{const input=fixture();input.transients[1234]=1;input.normalizedAmplitude[1234]=1;const result=refineDjBeatCandidates(input);assert.equal(result.candidates.some(x=>x.index===1234),false);});
test("B8 quiet intro does not generate false beats",()=>{const result=refineDjBeatCandidates(fixture({quietIntro:true}));assert.equal(result.candidates.some(x=>x.time<12),false);assert.ok(result.candidateCount>100);});
test("B8 dense 170 BPM material stays bounded and stable",()=>{const result=refineDjBeatCandidates(fixture({bpm:170,duplicates:true}));assert.ok(result.candidateCount<=8192);assert.ok(result.stability>.65);});
test("B8 natural live jitter retains a supported sequence",()=>{const result=refineDjBeatCandidates(fixture({bpm:128,jitter:.025}));assert.ok(result.candidateCount>100);assert.ok(result.liveTolerance>.55);});
test("B8 clipping does not multiply beat candidates",()=>{const normal=refineDjBeatCandidates(fixture()),clipped=refineDjBeatCandidates(fixture({clipped:true}));assert.ok(clipped.candidateCount<=normal.candidateCount+1);});
test("B8 never mutates prepared input or B4 evidence",()=>{const input=fixture({duplicates:true}),before=JSON.stringify(input);refineDjBeatCandidates(input);assert.equal(JSON.stringify(input),before);});

test("B8 cache fingerprint is independent from waveform and existing analysis assets",()=>{const changed={...DJ_IMPLEMENTATION_VERSIONS,beatDetection:"beat-refinement-future"};for(const type of ["prepared-waveform","waveform-detail","prepared-analysis","bpm-analysis","downbeat-analysis","dynamic-analysis","beat-grid"] as const)assert.equal(createDjImplementationFingerprint(type).value,createDjImplementationFingerprint(type,changed).value);assert.notEqual(createDjImplementationFingerprint("beat-detection").value,createDjImplementationFingerprint("beat-detection",changed).value);});
