import { DjBpmAnalysisResult, DjCanonicalBpmInput, selectDjOnsetCandidates } from "./djBpmAnalysis";
import { DjDownbeatAnalysisResult } from "./djDownbeatAnalysis";
import { normaliseDjConfidence } from "./djAnalysisConfidence";

export const DJ_DYNAMIC_ANALYSIS_FORMAT_VERSION = "dynamic-segments-v1";
export const DJ_DYNAMIC_MAX_WINDOWS = 12;
export const DJ_DYNAMIC_MAX_SEGMENTS = 8;

export type DjDynamicSegment = { id: string; startTime: number; startBeat: number; bpm: number; confidence: number; boundaryConfidence: number; mergeConfidence: number; evidenceWindows: number; };
export type DjDynamicAnalysisResult = { formatVersion: typeof DJ_DYNAMIC_ANALYSIS_FORMAT_VERSION; resolvedMode: "normal" | "dynamic"; constantBpmConfidence: number; dynamicConfidence: number; reviewRequired: boolean; resultState: "constant-high" | "constant-medium" | "dynamic-high" | "dynamic-medium" | "insufficient-evidence" | "review-required"; reasonCodes: string[]; spreadBpm: number; driftBpm: number; phaseResidual: number; coverage: number; observations: Array<{ time: number; bpm: number; confidence: number; phaseResidual: number }>; segments: DjDynamicSegment[]; analysedAt: string; };
export type DjDynamicInput = DjCanonicalBpmInput & { bpmAnalysis: DjBpmAnalysisResult; downbeatAnalysis: DjDownbeatAnalysisResult; };

const clamp=normaliseDjConfidence;const round=(v:number,d=6)=>Number((Number(v)||0).toFixed(d));
function quantile(values:number[],q:number){const a=values.filter(Number.isFinite).slice().sort((x,y)=>x-y);return a.length?a[Math.min(a.length-1,Math.max(0,Math.floor((a.length-1)*q)))]||0:0;}
function median(values:number[]){return quantile(values,0.5);}
function linearFit(points:Array<{beat:number;time:number}>){const n=points.length;if(n<2)return null;const mb=points.reduce((s,p)=>s+p.beat,0)/n,mt=points.reduce((s,p)=>s+p.time,0)/n;let top=0,bottom=0;for(const p of points){top+=(p.beat-mb)*(p.time-mt);bottom+=(p.beat-mb)**2;}if(!bottom)return null;const period=top/bottom,anchor=mt-period*mb;const residuals=points.map(p=>Math.abs(p.time-(anchor+p.beat*period))/Math.max(.001,period));return {period,residual:median(residuals)};}
function mergeSegments(segments:DjDynamicSegment[]){let current=segments.slice();let changed=true;while(changed&&current.length>1){changed=false;for(let i=1;i<current.length;i++){const left=current[i-1],right=current[i];const distance=Math.abs(left.bpm-right.bpm);if(distance<=0.25||right.boundaryConfidence<0.58||right.evidenceWindows<3){const total=left.evidenceWindows+right.evidenceWindows;left.bpm=round((left.bpm*left.evidenceWindows+right.bpm*right.evidenceWindows)/Math.max(1,total),3);left.confidence=clamp((left.confidence+right.confidence)/2);left.mergeConfidence=clamp(1-Math.min(1,distance/.5));left.evidenceWindows=total;current.splice(i,1);changed=true;break;}}}return current.slice(0,DJ_DYNAMIC_MAX_SEGMENTS).map((segment,index)=>({...segment,id:`segment-${index+1}`}));}

export function analyseDjDynamicTempo(input:DjDynamicInput):DjDynamicAnalysisResult{
 const analysedAt=input.analysedAt||new Date().toISOString();const baseBpm=Number(input.bpmAnalysis?.bpm),duration=Math.max(0,Number(input.duration)||0);const anchor=Number(input.downbeatAnalysis?.gridAnchorTime);const empty: DjDynamicAnalysisResult={formatVersion:DJ_DYNAMIC_ANALYSIS_FORMAT_VERSION,resolvedMode:"normal",constantBpmConfidence:0,dynamicConfidence:0,reviewRequired:true,resultState:"insufficient-evidence",reasonCodes:["insufficient-timing-observations"],spreadBpm:0,driftBpm:0,phaseResidual:1,coverage:0,observations:[],segments:[],analysedAt};if(!duration||!Number.isFinite(baseBpm)||!Number.isFinite(anchor))return empty;
 const period=60/baseBpm,onsets=selectDjOnsetCandidates(input);if(onsets.length<12)return empty;const unique=new Map<number,typeof onsets[number]>();for(const onset of onsets){const beat=Math.round((onset.time-anchor)/period),existing=unique.get(beat);if(!existing||onset.strength*onset.confidence>existing.strength*existing.confidence)unique.set(beat,onset);}const beats=Array.from(unique.entries()).map(([beat,onset])=>({beat,time:onset.time,strength:onset.strength,confidence:onset.confidence})).sort((a,b)=>a.time-b.time);
 const windowSeconds=Math.max(24,Math.min(42,duration*.1)),windowCount=Math.max(6,Math.min(DJ_DYNAMIC_MAX_WINDOWS,Math.round(duration/35)+4)),latest=Math.max(0,duration-windowSeconds),observations:DjDynamicAnalysisResult["observations"]=[];for(let i=0;i<windowCount;i++){const start=latest*(windowCount===1?0:i/(windowCount-1)),end=start+windowSeconds,local=beats.filter(p=>p.time>=start&&p.time<=end);if(local.length<8||local[local.length-1].beat-local[0].beat<16)continue;const localPeriods:number[]=[];for(let point=1;point<local.length;point++){const interval=local[point].time-local[point-1].time;if(interval<=0)continue;const beatMultiple=Math.max(1,Math.round(interval/period));const localBpm=60*beatMultiple/interval;if(Math.abs(localBpm-baseBpm)<=12)localPeriods.push(60/localBpm);}if(localPeriods.length<6)continue;const localPeriod=median(localPeriods),bpm=60/localPeriod;const residual=median(localPeriods.map(value=>Math.abs(value-localPeriod)/localPeriod));const activity=local.reduce((sum,p)=>sum+p.strength*p.confidence,0)/local.length;const confidence=clamp(activity*.42+Math.min(1,local.length/32)*.28+Math.max(0,1-residual*5)*.3);if(confidence<.32)continue;observations.push({time:round((start+end)/2,3),bpm:round(bpm,3),confidence,phaseResidual:round(residual,6)});}
 if(observations.length<4)return {...empty,observations,coverage:clamp(observations.length/windowCount)};const smoothed=observations.map((o,i)=>({...o,bpm:round(median(observations.slice(Math.max(0,i-1),Math.min(observations.length,i+2)).map(v=>v.bpm)),3)}));const bpms=smoothed.map(o=>o.bpm),spread=quantile(bpms,.9)-quantile(bpms,.1),drift=bpms[bpms.length-1]-bpms[0],phaseResidual=median(smoothed.map(o=>o.phaseResidual)),coverage=clamp(observations.length/windowCount);
 const exactDigital=input.bpmAnalysis.resultState==="exact-digital"&&input.bpmAnalysis.sectionAgreement>=.75&&input.bpmAnalysis.phaseError<=.08;const noiseAllowance=exactDigital?.55:.32;const rawRuns:Array<{points:typeof smoothed}>=[];for(let i=0;i<smoothed.length;i++){const point=smoothed[i];if(!rawRuns.length){rawRuns.push({points:[point]});continue;}const run=rawRuns[rawRuns.length-1],runBpm=median(run.points.map(p=>p.bpm)),next=smoothed[i+1],next2=smoothed[i+2];const supported=next&&next2&&Math.abs(next.bpm-point.bpm)<=.34&&Math.abs(next2.bpm-point.bpm)<=.45;const change=Math.abs(point.bpm-runBpm);if(change>=Math.max(.48,noiseAllowance)&&supported)rawRuns.push({points:[point]});else run.points.push(point);}
 let startBeat=0;const proposed:DjDynamicSegment[]=rawRuns.map((run,index)=>{const bpm=median(run.points.map(p=>p.bpm)),confidence=clamp(run.points.reduce((s,p)=>s+p.confidence,0)/run.points.length),boundary=index?clamp(Math.min(1,Math.abs(bpm-median(rawRuns[index-1].points.map(p=>p.bpm)))/1.2)*.5+Math.min(1,run.points.length/3)*.3+Math.min(1,rawRuns[index-1].points.length/3)*.2):1;const startTime=index?round((rawRuns[index - 1].points[rawRuns[index - 1].points.length - 1].time+run.points[0].time)/2,6):anchor;return {id:`segment-${index+1}`,startTime,startBeat,bpm:round(bpm,3),confidence,boundaryConfidence:boundary,mergeConfidence:clamp(1-Math.min(1,Math.abs(bpm-baseBpm)/1.5)),evidenceWindows:run.points.length};});
 for(let index=1;index<proposed.length;index++){const previous=proposed[index-1],current=proposed[index];current.startBeat=round(previous.startBeat+(current.startTime-previous.startTime)*previous.bpm/60,6);}
 const segments=mergeSegments(proposed),runRange=segments.length?Math.max(...segments.map(s=>s.bpm))-Math.min(...segments.map(s=>s.bpm)):0,sustained=segments.length>1&&segments.every(s=>s.evidenceWindows>=3&&s.confidence>=.48)&&(runRange>=.55||Math.abs(drift)>=.65),dynamicConfidence=clamp(runRange/2*.34+Math.abs(drift)/2*.18+coverage*.18+Math.max(0,1-phaseResidual*5)*.15+(segments.length>1?.15:0)),constantConfidence=clamp((exactDigital?.28:0)+Math.max(0,1-spread/1.2)*.34+Math.max(0,1-Math.abs(drift)/1.2)*.2+Math.max(0,1-phaseResidual*5)*.12+coverage*.12);const dynamic=sustained&&dynamicConfidence>=.62&&!exactDigital;const reasonCodes:string[]=[];if(!dynamic&&spread>.45)reasonCodes.push("timing-variation-without-sustained-boundary");if(phaseResidual>.16)reasonCodes.push("noisy-or-human-timing");if(coverage<.5)reasonCodes.push("sparse-percussion-coverage");if(exactDigital)reasonCodes.push("digital-constant-tempo-preferred");const review=dynamic?dynamicConfidence<.7:constantConfidence<.52&&spread>.45;return {formatVersion:DJ_DYNAMIC_ANALYSIS_FORMAT_VERSION,resolvedMode:dynamic?"dynamic":"normal",constantBpmConfidence:constantConfidence,dynamicConfidence,reviewRequired:review,resultState:review?"review-required":dynamic?(dynamicConfidence>=.78?"dynamic-high":"dynamic-medium"):(constantConfidence>=.75?"constant-high":"constant-medium"),reasonCodes,spreadBpm:round(spread,3),driftBpm:round(drift,3),phaseResidual:round(phaseResidual,6),coverage,observations:smoothed,segments:dynamic?segments:[{id:"segment-1",startTime:anchor,startBeat:0,bpm:baseBpm,confidence:constantConfidence,boundaryConfidence:1,mergeConfidence:1,evidenceWindows:observations.length}],analysedAt};
}
