import assert from "node:assert/strict";import test from "node:test";import { analyseDjDynamicTempo } from "./djDynamicAnalysis";
import { createDjImplementationFingerprint, DJ_IMPLEMENTATION_VERSIONS } from "./djPreparedAssets";
function fixture(kind:"constant"|"step"|"gradual"|"jitter"="constant"){const duration=180,fps=80,count=duration*fps,transients=new Array<number>(count).fill(0),energyWindows=new Array<number>(count).fill(.02),normalizedAmplitude=new Array<number>(count).fill(.03),windowConfidence=new Array<number>(count).fill(1);let time=.2,beat=0;while(time<duration){let bpm=120;if(kind==="step"&&time>=90)bpm=124;if(kind==="gradual")bpm=120+(time/duration)*3;if(kind==="jitter")time+=(beat%2?-.025:.025);const i=Math.max(0,Math.min(count-1,Math.round(time*fps)));transients[i]=1;energyWindows[i]=beat%16===0?1:.7;normalizedAmplitude[i]=.85;time+=60/bpm;beat++;}const selected=kind==="step"?122:kind==="gradual"?121.5:120;return {duration,transients,energyWindows,normalizedAmplitude,windowConfidence,analysedAt:"2026-07-27T00:00:00.000Z",bpmAnalysis:{bpm:selected,resultState:kind==="constant"?"exact-digital":"high-confidence",sectionAgreement:1,phaseError:.02} as any,downbeatAnalysis:{gridAnchorTime:.2} as any};}
test("B6 digital constant tempo remains Normal with one segment",()=>{const r=analyseDjDynamicTempo(fixture());assert.equal(r.resolvedMode,"normal");assert.equal(r.segments.length,1);assert.equal(r.segments[0].bpm,120);});
test("B6 minor human timing variation does not create segments",()=>{const r=analyseDjDynamicTempo(fixture("jitter"));assert.equal(r.resolvedMode,"normal",JSON.stringify(r));assert.equal(r.segments.length,1);});
test("B6 sustained step tempo creates bounded supported segments",()=>{const r=analyseDjDynamicTempo(fixture("step"));assert.equal(r.resolvedMode,"dynamic",JSON.stringify(r));assert.ok(r.segments.length>=2&&r.segments.length<=8);assert.ok(r.segments.slice(1).every(s=>s.boundaryConfidence>=.58&&s.evidenceWindows>=3));});
test("B6 gradual live drift is dynamic only with sustained evidence",()=>{const r=analyseDjDynamicTempo(fixture("gradual"));assert.ok(["normal","dynamic"].includes(r.resolvedMode));if(r.resolvedMode==="dynamic")assert.ok(r.dynamicConfidence>=.62);});
test("B6 isolated duplicate transient does not force Dynamic",()=>{const input=fixture();input.transients[4001]=.9;const r=analyseDjDynamicTempo(input);assert.equal(r.resolvedMode,"normal");assert.equal(r.segments.length,1);});
test("B6 missing beats and quiet edges preserve constant model",()=>{const input=fixture();for(let i=0;i<input.transients.length;i++){if(i<input.transients.length*.08||i>input.transients.length*.9||i%997===0)input.transients[i]=0;}const r=analyseDjDynamicTempo(input);assert.equal(r.resolvedMode,"normal",JSON.stringify(r));});
test("B6 output is deterministic and never changes B4/B5 inputs",()=>{const input=fixture("step"),before=JSON.stringify(input);const a=analyseDjDynamicTempo(input),b=analyseDjDynamicTempo(input);assert.deepEqual(a,b);assert.equal(JSON.stringify(input),before);});
test("B6 produces no redundant adjacent near-equal segments",()=>{const r=analyseDjDynamicTempo(fixture("step"));for(let i=1;i<r.segments.length;i++)assert.ok(Math.abs(r.segments[i].bpm-r.segments[i-1].bpm)>.25);});
test("B6 cache fingerprint is independent from waveform, BPM, downbeat and grid assets",()=>{const changed={...DJ_IMPLEMENTATION_VERSIONS,dynamicAnalysis:"dynamic-segments-future"};for(const type of ["prepared-waveform","waveform-detail","prepared-analysis","bpm-analysis","downbeat-analysis","beat-grid"] as const)assert.equal(createDjImplementationFingerprint(type).value,createDjImplementationFingerprint(type,changed).value);assert.notEqual(createDjImplementationFingerprint("dynamic-analysis").value,createDjImplementationFingerprint("dynamic-analysis",changed).value);});
