import assert from "node:assert/strict";import test from "node:test";import { reconcileDjFinalGrid } from "./djFinalGridDecision";import { DJ_BPM_ANALYSIS_FORMAT_VERSION } from "./djBpmAnalysis";import { DJ_DOWNBEAT_ANALYSIS_FORMAT_VERSION } from "./djDownbeatAnalysis";import { DJ_DYNAMIC_ANALYSIS_FORMAT_VERSION } from "./djDynamicAnalysis";import { DJ_BEAT_DETECTION_FORMAT_VERSION } from "./djBeatDetection";import { DJ_GRID_VALIDATION_FORMAT_VERSION } from "./djGridValidation";
import { createDjImplementationFingerprint, DJ_IMPLEMENTATION_VERSIONS } from "./djPreparedAssets";
function fixture(o:{dynamic?:boolean;warning?:boolean;low?:boolean;insufficient?:boolean;conflict?:string;manual?:boolean;locked?:boolean;existing?:boolean}={}){const segment={id:"segment-1",startTime:.2,startBeat:0,bpm:120,confidence:o.warning?.62:.9,boundaryConfidence:o.warning?.62:1,mergeConfidence:1,evidenceWindows:8};const second={...segment,id:"segment-2",startTime:90,startBeat:180,bpm:124,boundaryConfidence:.9};const reasons=o.conflict?[o.conflict]:[];return {analysedAt:"2026-07-27T00:00:00.000Z",bpmAnalysis:{formatVersion:DJ_BPM_ANALYSIS_FORMAT_VERSION,bpm:120,confidence:o.low?.3:o.warning?.64:.9,octaveAmbiguous:false} as any,downbeatAnalysis:{formatVersion:DJ_DOWNBEAT_ANALYSIS_FORMAT_VERSION,gridAnchorTime:.2,firstStableBeatTime:.2,selectedBarOffset:0,downbeatConfidence:o.low?.4:.9,phraseAgreement:.85} as any,dynamicAnalysis:{formatVersion:DJ_DYNAMIC_ANALYSIS_FORMAT_VERSION,resolvedMode:o.dynamic?"dynamic":"normal",segments:o.dynamic?[segment,second]:[segment],dynamicConfidence:.9,constantBpmConfidence:o.warning?.64:.9} as any,beatDetection:{formatVersion:DJ_BEAT_DETECTION_FORMAT_VERSION,candidateCount:o.insufficient?4:300,candidates:[]} as any,gridValidation:{formatVersion:DJ_GRID_VALIDATION_FORMAT_VERSION,resultState:o.insufficient?"insufficient-evidence":reasons.length?"review-required":"valid",reviewRequired:reasons.length>0,preferredMode:o.dynamic?"dynamic":"normal",recommendedSegments:o.dynamic?[segment,second]:[segment],confidenceAfter:o.warning?.64:.9,correctionBenefit:o.dynamic?.12:0,reasonCodes:reasons,analysedAt:"2026-07-27T00:00:00.000Z"} as any,existingGrid:o.manual||o.locked||o.existing?{manual:o.manual,locked:o.locked,bpm:o.existing?121:120,firstBeatTime:o.existing?.3:.2,barOffset:0,segments:[segment],alignmentConfidence:.6}:undefined};}
test("B10 accepts high-confidence constant grid",()=>{const r=reconcileDjFinalGrid(fixture());assert.equal(r.outcome,"accepted");assert.ok(r.reasonCodes.includes("high-confidence-constant-grid"));});
test("B10 accepts high-confidence Dynamic grid",()=>{const r=reconcileDjFinalGrid(fixture({dynamic:true}));assert.equal(r.outcome,"accepted");assert.ok(r.reasonCodes.includes("high-confidence-dynamic-grid"));});
test("B10 supports accepted-with-warning",()=>{assert.equal(reconcileDjFinalGrid(fixture({warning:true})).outcome,"accepted-with-warning");});
test("B10 low confidence requires review",()=>{assert.equal(reconcileDjFinalGrid(fixture({low:true})).outcome,"review-required");});
test("B10 insufficient rhythmic evidence defers",()=>{assert.equal(reconcileDjFinalGrid(fixture({insufficient:true})).outcome,"insufficient-evidence");});
test("B10 malformed upstream analysis is invalid",()=>{const i=fixture();i.bpmAnalysis.bpm=NaN;assert.equal(reconcileDjFinalGrid(i).outcome,"analysis-invalid");});
test("B10 unsupported version is invalid",()=>{const i=fixture();i.gridValidation.formatVersion="future";assert.equal(reconcileDjFinalGrid(i).outcome,"analysis-invalid");});
test("B10 B4 versus B9 drift conflict requires review",()=>{const r=reconcileDjFinalGrid(fixture({conflict:"b4-bpm-conflict"}));assert.equal(r.outcome,"review-required");assert.ok(r.reasonCodes.includes("whole-track-drift-unresolved"));});
test("B10 B5 versus B9 conflict requires review",()=>{assert.equal(reconcileDjFinalGrid(fixture({conflict:"b5-downbeat-conflict"})).outcome,"review-required");});
test("B10 B6 versus B9 disagreement is explicit",()=>{const r=reconcileDjFinalGrid(fixture({dynamic:true,conflict:"dynamic-segments-no-material-benefit"}));assert.ok(["accepted-with-warning","review-required"].includes(r.outcome));assert.ok(r.reasonCodes.includes("dynamic-grid-no-material-benefit"));});
test("B10 manual grid is authoritative",()=>{const r=reconcileDjFinalGrid(fixture({manual:true}));assert.equal(r.outcome,"protected-existing-grid");assert.equal(r.protectedReason,"manual-grid-protected");});
test("B10 locked grid is authoritative",()=>{const r=reconcileDjFinalGrid(fixture({locked:true}));assert.equal(r.outcome,"protected-existing-grid");assert.equal(r.protectedReason,"locked-grid-protected");});
test("B10 compares existing generated grid",()=>{const r=reconcileDjFinalGrid(fixture({existing:true}));assert.equal(r.existingGridComparison.available,true);assert.equal(r.existingGridComparison.materiallyDifferent,true);assert.equal(r.outcome,"review-required");});
test("B10 groups duplicate-derived evidence once",()=>{const r=reconcileDjFinalGrid(fixture());assert.equal(r.diagnostics.ignoredDuplicateEvidence.length,2);assert.deepEqual(Object.keys(r.diagnostics.categories),["tempo","anchor","model","wholeTrack"]);});
test("B10 repeated execution is deterministic",()=>{const i=fixture({dynamic:true});assert.deepEqual(reconcileDjFinalGrid(i),reconcileDjFinalGrid(i));});
test("B10 legacy cache without reconciliation remains usable upstream",()=>{const i=fixture();assert.equal((i as any).finalGridDecision,undefined);assert.equal(reconcileDjFinalGrid(i).outcome,"accepted");});
test("B10 invalid reconciliation metadata can be ignored",()=>{const i:any=fixture();i.finalGridDecision={formatVersion:"future",outcome:"accepted"};delete i.finalGridDecision;assert.equal(reconcileDjFinalGrid(i).outcome,"accepted");});
test("B10 never mutates B4-B9 or existing grid",()=>{const i=fixture({dynamic:true,existing:true}),before=JSON.stringify(i);reconcileDjFinalGrid(i);assert.equal(JSON.stringify(i),before);});

test("B10 cache fingerprint is independent from waveform and B4-B9 assets",()=>{const changed={...DJ_IMPLEMENTATION_VERSIONS,finalGridDecision:"final-grid-decision-future"};for(const type of ["prepared-waveform","waveform-detail","prepared-analysis","bpm-analysis","beat-detection","downbeat-analysis","dynamic-analysis","grid-validation","beat-grid"] as const)assert.equal(createDjImplementationFingerprint(type).value,createDjImplementationFingerprint(type,changed).value);assert.notEqual(createDjImplementationFingerprint("final-grid-decision").value,createDjImplementationFingerprint("final-grid-decision",changed).value);});
