import assert from "node:assert/strict";import test from "node:test";import { validateDjWholeTrackGrid } from "./djGridValidation";
import { createDjImplementationFingerprint, DJ_IMPLEMENTATION_VERSIONS } from "./djPreparedAssets";
function fixture(o:{actual?:number;selected?:number;dynamic?:boolean;noise?:number;quiet?:boolean;lateShift?:number;anchor?:number;protected?:"locked"|"manual";redundant?:boolean}={}){const duration=180,selected=o.selected||120,anchor=o.anchor??.2,candidates:any[]=[];let time=.2,beat=0;while(time<duration){const actual=o.dynamic&&time>=90?124:(o.actual||120),quiet=o.quiet&&(time<15||time>165),noise=(o.noise||0)*(beat%2?1:-1),late=o.lateShift&&time>125?o.lateShift:0;if(!quiet)candidates.push({index:beat,time:time+noise+late,strength:1,confidence:.9,validationConfidence:.9,spacingConfidence:.9,contextConfidence:.9,character:"kick-like",reasonCodes:[]});time+=60/actual;beat++;}const first={id:"segment-1",startTime:anchor,startBeat:0,bpm:o.dynamic?120:selected,confidence:.8,boundaryConfidence:1,mergeConfidence:1,evidenceWindows:5},second={id:"segment-2",startTime:90,startBeat:(90-anchor)*120/60,bpm:o.redundant?120.1:124,confidence:.8,boundaryConfidence:o.redundant?.5:.9,mergeConfidence:.2,evidenceWindows:4};return {duration,bpmAnalysis:{bpm:selected,confidence:.8,analysedAt:"2026-07-27T00:00:00.000Z"} as any,downbeatAnalysis:{gridAnchorTime:anchor,downbeatConfidence:.8} as any,dynamicAnalysis:{resolvedMode:o.dynamic||o.redundant?"dynamic":"normal",segments:o.dynamic||o.redundant?[first,second]:[first],dynamicConfidence:.8,constantBpmConfidence:.8,analysedAt:"2026-07-27T00:00:00.000Z"} as any,beatDetection:{candidates,candidateCount:candidates.length,analysedAt:"2026-07-27T00:00:00.000Z"} as any,protectedGrid:o.protected?{[o.protected]:true}:undefined,analysedAt:"2026-07-27T00:00:00.000Z"};}
test("B9 stable digital track has no drift",()=>{const r=validateDjWholeTrackGrid(fixture());assert.equal(r.resultState,"valid");assert.equal(r.preferredMode,"normal");assert.ok(r.constantMetrics.withinTolerance>.95);});
test("B9 noisy constant track remains Normal",()=>{const r=validateDjWholeTrackGrid(fixture({noise:.012}));assert.equal(r.preferredMode,"normal");assert.equal(r.reviewRequired,false);});
test("B9 wrong constant BPM reports conflict without replacing B4",()=>{const i=fixture({actual:120,selected:119.5}),b=i.bpmAnalysis.bpm,r=validateDjWholeTrackGrid(i);assert.equal(i.bpmAnalysis.bpm,b);assert.equal(r.reviewRequired,true);assert.equal(r.autoApplicable,false);});
test("B9 true Dynamic map improves alignment",()=>{const r=validateDjWholeTrackGrid(fixture({dynamic:true,selected:122}));assert.equal(r.preferredMode,"dynamic",JSON.stringify(r));assert.ok(r.correctionBenefit>=.08);});
test("B9 redundant Dynamic segment is rejected",()=>{const r=validateDjWholeTrackGrid(fixture({redundant:true}));assert.equal(r.preferredMode,"normal");assert.equal(r.recommendedSegments.length,1);});
test("B9 isolated weak breakdown does not force review",()=>{const i=fixture();i.beatDetection.candidates=i.beatDetection.candidates.filter((x:any)=>x.time<80||x.time>100);assert.equal(validateDjWholeTrackGrid(i).reviewRequired,false);});
test("B9 quiet intro and outro validate safely",()=>{const r=validateDjWholeTrackGrid(fixture({quiet:true}));assert.ok(r.constantMetrics.validatedBeats>100);assert.equal(r.reviewRequired,false);});
test("B9 incorrect late alignment is reported",()=>{const r=validateDjWholeTrackGrid(fixture({lateShift:.08}));assert.equal(r.reviewRequired,true);assert.ok(r.constantMetrics.lateError>r.constantMetrics.earlyError);});
test("B9 B5 disagreement is report-only",()=>{const r=validateDjWholeTrackGrid(fixture({anchor:.32}));assert.ok(r.reasonCodes.includes("b5-downbeat-conflict"));assert.equal(r.autoApplicable,false);});
test("B9 locked grid remains protected",()=>{const r=validateDjWholeTrackGrid(fixture({actual:120,selected:119.5,protected:"locked"}));assert.equal(r.protected,true);assert.equal(r.autoApplicable,false);});
test("B9 manual grid remains protected",()=>{const r=validateDjWholeTrackGrid(fixture({anchor:.32,protected:"manual"}));assert.equal(r.protected,true);assert.equal(r.protectedDisagreement,true);});
test("B9 execution is deterministic",()=>{const i=fixture({dynamic:true,selected:122});assert.deepEqual(validateDjWholeTrackGrid(i),validateDjWholeTrackGrid(i));});
test("B9 legacy cache without validation fails safely",()=>{const i=fixture();i.beatDetection={candidates:[],candidateCount:0} as any;assert.equal(validateDjWholeTrackGrid(i).resultState,"insufficient-evidence");});
test("B9 invalid validation metadata is ignored",()=>{const i=fixture();i.beatDetection.candidates.push({time:NaN,validationConfidence:NaN} as any);assert.ok(Number.isFinite(validateDjWholeTrackGrid(i).constantGridScore));});
test("B9 review threshold ignores weak region and catches sustained conflict",()=>{assert.equal(validateDjWholeTrackGrid(fixture()).reviewRequired,false);assert.equal(validateDjWholeTrackGrid(fixture({actual:120,selected:119.5})).reviewRequired,true);});
test("B9 never mutates B4-B8 inputs",()=>{const i=fixture({dynamic:true,selected:122}),before=JSON.stringify(i);validateDjWholeTrackGrid(i);assert.equal(JSON.stringify(i),before);});

test("B9 cache fingerprint is independent from waveform and B4-B8 assets",()=>{const changed={...DJ_IMPLEMENTATION_VERSIONS,gridValidation:"whole-track-grid-future"};for(const type of ["prepared-waveform","waveform-detail","prepared-analysis","bpm-analysis","beat-detection","downbeat-analysis","dynamic-analysis","beat-grid"] as const)assert.equal(createDjImplementationFingerprint(type).value,createDjImplementationFingerprint(type,changed).value);assert.notEqual(createDjImplementationFingerprint("grid-validation").value,createDjImplementationFingerprint("grid-validation",changed).value);});
